tasks:
 - name: setup bit and pnpm
   init: >
      mkdir -p  /workspace/.npm/node_modules
      gp env NPM_CONFIG_PREFIX=/workspace/.npm/node_modules &&
      eval $(gp env -e) &&
      export PATH=/workspace/bin:/workspace/.npm/node_modules/bin:$HOME/bin:$PATH &&
      npm i -g @teambit/bvm &&
      BVM_GLOBALS_DIR=/workspace/.bvm/ bvm install &&
      npm i -g pnpm
   command: >
      eval $(gp env -e) &&
      export PATH=/workspace/bin:/workspace/.npm/node_modules/bin:$HOME/bin:$PATH &&
      echo "export PATH=/workspace/bin:/workspace/.npm/node_modules/bin:$HOME/bin:$PATH" >> /home/gitpod/.bashrc &&
      bit config set analytics_reporting false &&
      bit config set error_reporting false &&
      bit config set user.token $BIT_TOKEN &&
      bit import &&
      bit install &&
      gp sync-done bit-installed &&
      bit compile &&
      bit link
vscode:
  extensions:
    - esbenp.prettier-vscode
    - GitHub.copilot
